import type { Metadata } from "next";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import theme from "./theme";
import { ThemeProvider } from "@mui/material";
import Header from "./entities/header/header";
import Footer from "./components/footer";
import { ShopStoreProvider } from "./providers/store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className=""
        >
          <ShopStoreProvider>
            <Header />
            {children}
            <Footer />
          </ShopStoreProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
